<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mzl</string>
	</array>
	<key>name</key>
	<string>Sublime Maze</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>This pattern matches the walls of the maze</string>
			<key>match</key>
			<string>[\[,\]]</string>
			<key>name</key>
			<string>entity.wall.mzl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>This pattern matches the player charactere</string>
			<key>match</key>
			<string>[\u25C4,\u25BA,\u25B2,\u25BC]</string>
			<key>name</key>
			<string>entity.player.mzl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>This pattern matches the Start point of a maze</string>
			<key>match</key>
			<!-- <string>[ \u2123 ]</string> -->
			<string>[ S ]</string>
			<key>name</key>
			<string>entity.startpt.mzl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>This pattern matches the End point of a maze</string>
			<key>match</key>
			<string>[ \u2134 ]</string>
			<!-- <string>[ \u25BC, E ]</string> -->
			<key>name</key>
			<string>entity.endpt.mzl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mzl</string>
	<key>uuid</key>
	<string>43803c00-147b-40e2-b3b1-a7a0a9e5a445</string>
</dict>
</plist>
